- name: loop test
  hosts: localhost
  gather_facts: no
  become: no
  vars:
    - var1 : { include: include/user.yaml, vars: {name: 'timmy', age: 20}, tags: t3 }
    - var2 : { include: include/user.yaml, vars: [name: 'timmy', age: 20], tags: t3 }
  tasks:
  - debug:
      msg: "{{ var1 }}"
  - debug:
      msg: "{{ var2 }}"
