- hosts: slave
  gather_facts: no
  become: yes
  tasks:
  - name: crate a filesystem from a block device
    filesystem:
      dev: /dev/xvdf
      force: yes
      fstype: ext4
    register: output
  - debug: msg={{ output }}
  - name: mount the fs in the system
    mount:
      src: /dev/xvdf
      path: /mnt/test
      fstype: ext4
      state: mounted
#[mounted]: the device will be actively mounted and appropriately configured in fstab. If the mount point is not present, the mount point will be created.
#[unmounted]: the device will be unmounted without changing fstab.
#[present] only specifies that the device is to be configured in fstab and does not trigger or require a mount.
#[absent] specifies that the device mount's entry will be removed from fstab and will also unmount the device and remove the mount point.
#[remounted] specifies that the device will be remounted for when you want to force a refresh on the mount itself (added in 2.9). This will always return changed=true.