- hosts: slave
  tasks:
  - wait_for:
      port: 22
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      delay: 10
      search_regex: OpenSSH
      state: started
    register: waitfor
    delegate_to: localhost #test the remote port from localhost
  - debug: 
      msg: "{{ waitfor }}"