- name: instsall the ius repo on slave
  hosts: slave
  gather_facts: no
  become: yes
  tasks:
  - name: copy gpg key file to remote client
    copy:
      src: ../vars/RPM-GPG-KEY-IUS-7
      dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-IUS-7
      owner: root
      group: root
      mode: "0644"
  - name: install ius.repo on slave
    yum_repository:
      name: "ius"
      description: "IUS for Enterprise Linux 7 - $basearch"
      baseurl: "https://repo.ius.io/7/$basearch/"
      enabled: yes
      gpgcheck: yes
      gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-IUS-7" 