- name: test palybook handlers
  hosts: slave
  gather_facts: no
  become: yes
  vars:
    - restart_time: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"
  tasks:
  - name: restart a chronyd service
    systemd:
      name: chronyd
      state: restarted
    notify: 
      - record restart time
  handlers:
  - name: record restart time
    shell:
      cmd: echo -e "restart chronyd on {{ restart_time }} \n" >> /home/centos/restart_chronyd.log
      