- hosts: localhost
  gather_facts: yes
  vars:
    - var_default1: ""
    - var_string1: "abc123ABV"
    - var_string2: " abc "
    - var_string3: "123456789"
    - var_string4: "sfacb1335@#$%"
    - var_num: -1
    - var_list1: [1,2,4,6,3,5]
    - var_list2: [1,[2,3,4,[5,6]]]
    - var_list3: [1,2,'a','b','cd']
    - var_list4: [1,'A','b',['C','d'],'Efg']
    - var_list5: ['abc',1,2,'a',3,2,'1','abc']
    - var_list6: ['abc',3,'1','b','a']
    - var_path: /home/centos/ansible/ansible.cfg.with_no_comment
    - var_home: ~/ansible/hosts
    - var_link: /home/centos/config.file
    - var_file:
        - path: /home/centos/file1
          mode: '0444'
        - path: /home/centos/file2
        - path: /home/centos/file3
    - var_json: '{"name":"anddy.liu","type":"file","server":"localhost","port":12843,"cipher":"chacha20-ietf","password":"justexample","udp":true}'
    - var_yaml: "{{ lookup('file','../vars/user.json') }}"
  vars_files:
    - ../vars/user.json
  tasks:
  - debug:
      msg: "{{ var_default2 | mandatory }}"
    ignore_errors: yes
  - debug:
      msg: "yaml-like vars without from_yaml -->{{ var_yaml | type_debug }}"
  - debug:
      msg: "yaml-like vars with from_yaml -->{{ var_yaml | from_yaml | type_debug }}"
  - debug:
      msg: "json-like vars without from_json -->{{ var_json  | type_debug }}"  
  - debug:
      msg: "json-like vars with from_json -->{{ var_json | from_json | type_debug }}"      
  - file:
      dest: "{{ item.path }}"
      state: touch
      mode: "{{ item.mode | default(omit) }}"
    loop: "{{ var_file }}"
  - command:
      cmd: echo "this is a test"
    register: echo_return
  - template:
      src: ../templates/filter.j2
      dest: ../tmp/filter.out